name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
      - "Cargo.toml"
      - "Dockerfile"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
      - "Cargo.toml"
      - "Dockerfile"

concurrency:
  group: "hello"
  cancel-in-progress: true

jobs:
  client:
    environment: stage
    runs-on: ubuntu-latest
    env:
      IMAGE: dagandersen/hello-world
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'prod' || 'dev' }}-${sha}-${ts}" 

      - name: Build and publish container image with tag
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}  
