name: manual-commit

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/manual-commit.yml"
      - "Cargo.toml"
      - "Dockerfile"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/manual-commit.yml"
      - "Cargo.toml"
      - "Dockerfile"

env:
  APP-VERSION: ${{ github.run_id }}
  IMAGE_NAME: dagandersen/visma-sre

permissions: write-all

jobs:
  service:
    environment: stage
    runs-on: ubuntu-latest
    env:
      IMAGE: dagandersen/visma-sre
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::gitops-${sha}-${ts}"

      - name: Build and publish container image with tag
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dag-andersen/visma-e-conomic-hiring
          fetch-depth: 0

      - uses: imranismail/setup-kustomize@v2
      - id: "kustomize-update-tag"
        name: "Update image tag using Kustomize"
        run: |

          cd k8s/dummy-pdf-or-png
          kustomize edit set image ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          git add kustomization.yml
          cd ../..

          git config --local user.email "bump-version-bump@github.com"
          git config --local user.name "github-actions-bump-version"

          git commit -m "Bump version [automated commit]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
